llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  google:
    provider: "google"
    model_name: "gemini-1.5-flash"
  huggingface:
    provider: "huggingface"
    model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
embeddings:
  huggingface:
    provider: "huggingface"
    model_name: "all-MiniLM-L6-v2"
    