export const clerkAppearance = {
  variables: {
    colorPrimary: '#7A5C3A',
    colorBackground: '#FFFCF5',
    colorText: '#2C2218',
    colorTextSecondary: '#6B5B47',
    colorInputBackground: '#EDE5D8',
    colorInputText: '#2C2218',
    borderRadius: '24px',
    fontFamily: '"DM Sans", sans-serif',
  },
  elements: {
    rootBox: 'mindmate-clerk-root',
    page: 'mindmate-clerk-page',
    pageScrollBox: 'mindmate-clerk-page-scroll',
    cardBox: 'mindmate-clerk-surface',
    card: 'mindmate-clerk-card',
    modalBackdrop: 'mindmate-clerk-modal-backdrop',
    modalContent: 'mindmate-clerk-surface mindmate-clerk-modal-content',
    headerTitle: 'mindmate-clerk-title',
    headerSubtitle: 'mindmate-clerk-subtitle',
    socialButtonsBlockButton: 'mindmate-clerk-button-secondary',
    socialButtonsBlockButtonText: 'mindmate-clerk-button-secondary-text',
    dividerLine: 'mindmate-clerk-divider-line',
    dividerText: 'mindmate-clerk-divider-text',
    formFieldLabel: 'mindmate-clerk-label',
    formFieldInput: 'mindmate-clerk-input',
    formFieldInputShowPasswordButton: 'mindmate-clerk-input-toggle',
    formButtonPrimary: 'mindmate-clerk-button-primary',
    footerAction: 'mindmate-clerk-footer-action',
    footerActionText: 'mindmate-clerk-footer-text',
    footerActionLink: 'mindmate-clerk-link',
    identityPreviewText: 'mindmate-clerk-label',
    identityPreviewEditButton: 'mindmate-clerk-link',
    formResendCodeLink: 'mindmate-clerk-link',
    alternativeMethodsBlockButton: 'mindmate-clerk-button-secondary',
    otpCodeFieldInput: 'mindmate-clerk-input mindmate-clerk-otp-input',
    alert: 'mindmate-clerk-alert',
    alertText: 'mindmate-clerk-alert-text',
    formFieldHintText: 'mindmate-clerk-hint',
    formFieldErrorText: 'mindmate-clerk-error',
    userButtonBox: 'mindmate-clerk-user-button',
    avatarBox: 'mindmate-clerk-avatar-box',
    userButtonPopoverCard: 'mindmate-clerk-surface mindmate-clerk-popover',
    userButtonPopoverMain: 'mindmate-clerk-popover-main',
    userButtonPopoverActions: 'mindmate-clerk-popover-actions',
    userPreview: 'mindmate-clerk-user-preview',
    userPreviewMainIdentifier: 'mindmate-clerk-user-main',
    userPreviewSecondaryIdentifier: 'mindmate-clerk-user-secondary',
    userButtonPopoverActionButton: 'mindmate-clerk-popover-action',
    userButtonPopoverActionButtonText: 'mindmate-clerk-popover-action-text',
    userButtonPopoverActionButtonIcon: 'mindmate-clerk-popover-action-icon',
    userButtonPopoverFooter: 'mindmate-clerk-popover-footer',
    navbar: 'mindmate-clerk-navbar',
    navbarButton: 'mindmate-clerk-navbar-button',
    badge: 'mindmate-clerk-badge',
  },
};
